version: '{{compose.fileVersion}}'
networks:
  {{server.serverExposedNetwork}}:
    external: true
  heimdall-stack-{{deployment.id}}:
  heimdall-data-network:
    external: true
services:
  consul-{{deployment.id}}:
    image: consul:latest
    container_name: consul-{{deployment.id}}
    networks:
      - heimdall-stack-{{deployment.id}}
  heimdall-api-gateway-{{deployment.id}}:
    image: {{images.apiGateway.imagePath}}:{{images.apiGateway.imageTag}}
    container_name: heimdall-api-gateway-{{deployment.id}}
    restart: {{deployment.restartPolicy}}
    networks:
      - heimdall-stack-{{deployment.id}}
      - {{server.serverExposedNetwork}}
    labels:
      - traefik.enable=true
      - traefik.http.routers.heimdall-api-webrouter-{{deployment.id}}.entrypoints=http
      - traefik.http.routers.heimdall-api-webrouter-{{deployment.id}}.rule=Host(`{{deployment.fullyQualifiedDomainName}}`)&&PathPrefix(`/api`)
      - traefik.http.middlewares.heimdall-api-securityredirect-{{deployment.id}}.redirectscheme.scheme=https
      - traefik.http.routers.heimdall-api-webrouter-{{deployment.id}}.middlewares=heimdall-api-securityredirect-{{deployment.id}}
      - traefik.http.routers.heimdall-api-securerouter-{{deployment.id}}.entrypoints=https
      - traefik.http.routers.heimdall-api-securerouter-{{deployment.id}}.rule=Host(`{{deployment.fullyQualifiedDomainName}}`)&&PathPrefix(`/api`)
      - traefik.http.routers.heimdall-api-securerouter-{{deployment.id}}.tls=true
      - traefik.http.routers.heimdall-api-securerouter-{{deployment.id}}.service=heimdall-api-gateway-{{deployment.id}}
      - traefik.http.services.heimdall-api-gateway-{{deployment.id}}.loadbalancer.server.port=8080
      - traefik.docker.network={{server.serverExposedNetwork}}
